import type { Metadata } from "next";
import { LegalShell, H2, P } from "../_shared/ui";

export const metadata: Metadata = {
  title: "Terms of Service — StemAI",
  description: "The terms for buying and using StemAI.",
};

export default function Terms() {
  return (
    <LegalShell title="Terms of Service" updated="June 2026">
      <P>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your purchase and use
        of StemAI (&ldquo;the Software,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;).
        By buying, downloading, or using StemAI you agree to these Terms. If you do
        not agree, do not use the Software.
      </P>

      <H2>Your license</H2>
      <P>
        Your purchase grants you a perpetual, non-exclusive, non-transferable
        license to install and use StemAI on computers you own or control, for
        personal or commercial work, subject to these Terms. The license includes
        updates we make generally available. You may not resell, redistribute,
        rent, sublicense, or share your license key, nor remove or alter any
        licensing or attribution notices.
      </P>

      <H2>What you create &amp; how you may use it</H2>
      <P>
        As between you and us, you own the audio you generate with StemAI, and we
        claim no ownership of your output. <strong>However</strong>, ownership is
        not the same as a clear, unrestricted copyright. Music generated by AI
        models carries important legal nuances you are responsible for
        understanding:
      </P>
      <P>
        <strong>(a) Underlying model license.</strong> StemAI generates audio with
        Stable Audio 3 (by Stability AI), provided under the Stability AI Community
        License. That license permits <strong>commercial use</strong> &mdash; you
        may sell, distribute, and monetize your tracks &mdash; for individuals and
        organizations under US $1,000,000 in annual revenue; above that threshold
        Stability&rsquo;s Enterprise license applies. Your use of the output is
        subject to that license. See our <a href="/ai-disclosure">AI Disclosure</a>{" "}
        for full attribution and training-data details.
      </P>
      <P>
        <strong>(b) Copyrightability.</strong> Under current U.S. Copyright Office
        guidance, purely AI-generated material without sufficient human authorship
        may not be eligible for copyright registration. The amount of protection
        available to a given track depends on your creative contribution. We make
        no representation that any output is registrable or protectable.
      </P>
      <P>
        <strong>(c) Your inputs.</strong> You are solely responsible for ensuring
        your prompts and any audio you import do not infringe anyone&rsquo;s
        copyright, trademark, publicity, or other rights, and that you have the
        rights to any material you upload for stem separation or editing.
      </P>
      <P>
        <strong>(d) Platform requirements.</strong> Streaming and distribution
        platforms increasingly require that AI-generated or AI-assisted music be
        disclosed. Complying with those requirements is your responsibility.
      </P>

      <H2>Acceptable use</H2>
      <P>
        You agree not to use StemAI to knowingly create material that infringes
        copyright or trademark, that unlawfully impersonates a real
        artist&rsquo;s voice or identity, that is defamatory, or that otherwise
        violates applicable law. You agree not to attempt to circumvent the license
        system, or to reverse-engineer, decompile, or disassemble the Software
        except to the limited extent that law expressly permits despite this
        restriction.
      </P>

      <H2>Third-party components</H2>
      <P>
        StemAI incorporates third-party open-source software and AI models, each
        governed by its own license. Your use of those components is subject to the
        applicable third-party terms, which are identified in the Software and our{" "}
        <a href="/ai-disclosure">AI Disclosure</a>. Nothing in these Terms limits
        your rights under any applicable open-source license.
      </P>

      <H2>Refunds</H2>
      <P>
        We offer a 14-day refund from the date of purchase &mdash; just email
        support. After a refund is issued, your license is deactivated and you must
        stop using the Software.
      </P>

      <H2>Disclaimer of warranties</H2>
      <P>
        StemAI is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo;
        without warranties of any kind, whether express, implied, or statutory,
        including any implied warranties of merchantability, fitness for a
        particular purpose, title, and non-infringement. We do not warrant that the
        Software will be error-free, that any output will be original, protectable,
        or free of third-party rights, or that it will meet your requirements.
      </P>

      <H2>Limitation of liability</H2>
      <P>
        To the maximum extent permitted by law, we will not be liable for any
        indirect, incidental, special, consequential, or punitive damages, or for
        lost profits, data, or goodwill, arising out of or relating to your use of
        the Software or any output &mdash; including any claim that output
        infringes a third party&rsquo;s rights. Our total aggregate liability for
        any claim is limited to the amount you actually paid for the Software. Some
        jurisdictions do not allow certain limitations, so parts of this section
        may not apply to you.
      </P>

      <H2>Indemnification</H2>
      <P>
        You agree to indemnify and hold us harmless from any claim arising out of
        your prompts, your imported material, or your use, distribution, or
        monetization of output in violation of these Terms or applicable law.
      </P>

      <H2>Governing law</H2>
      <P>
        These Terms are governed by the laws of the State of California, without
        regard to its conflict-of-laws rules, and you agree to the exclusive
        jurisdiction of the state and federal courts located in California, except
        where applicable consumer-protection law gives you the right to bring a
        claim elsewhere.
      </P>

      <H2>Changes</H2>
      <P>
        We may update these Terms; the effective date is shown above. Material
        changes will be noted on the site, and your continued use after changes
        take effect constitutes acceptance.
      </P>
    </LegalShell>
  );
}
