// Auto-generated GM instrument catalog for WebAudioFont (GeneralUser GS bank).
// 128 General MIDI programs grouped into 16 families. file = preset name on the CDN.
export interface WafInstrument { file: string; program: number; name: string; family: string; }
export const WAF_INSTRUMENTS: WafInstrument[] = [
  { file: "0000_GeneralUserGS_sf2_file", program: 0, name: "Acoustic Grand Piano", family: "Piano" },
  { file: "0010_GeneralUserGS_sf2_file", program: 1, name: "Bright Acoustic Piano", family: "Piano" },
  { file: "0020_GeneralUserGS_sf2_file", program: 2, name: "Electric Grand Piano", family: "Piano" },
  { file: "0030_GeneralUserGS_sf2_file", program: 3, name: "Honky-tonk Piano", family: "Piano" },
  { file: "0040_GeneralUserGS_sf2_file", program: 4, name: "Electric Piano 1 (Rhodes)", family: "Piano" },
  { file: "0050_GeneralUserGS_sf2_file", program: 5, name: "Electric Piano 2 (DX)", family: "Piano" },
  { file: "0060_GeneralUserGS_sf2_file", program: 6, name: "Harpsichord", family: "Piano" },
  { file: "0070_GeneralUserGS_sf2_file", program: 7, name: "Clavinet", family: "Piano" },
  { file: "0080_GeneralUserGS_sf2_file", program: 8, name: "Celesta", family: "Chromatic Percussion" },
  { file: "0090_GeneralUserGS_sf2_file", program: 9, name: "Glockenspiel", family: "Chromatic Percussion" },
  { file: "0100_GeneralUserGS_sf2_file", program: 10, name: "Music Box", family: "Chromatic Percussion" },
  { file: "0110_GeneralUserGS_sf2_file", program: 11, name: "Vibraphone", family: "Chromatic Percussion" },
  { file: "0120_GeneralUserGS_sf2_file", program: 12, name: "Marimba", family: "Chromatic Percussion" },
  { file: "0130_GeneralUserGS_sf2_file", program: 13, name: "Xylophone", family: "Chromatic Percussion" },
  { file: "0140_GeneralUserGS_sf2_file", program: 14, name: "Tubular Bells", family: "Chromatic Percussion" },
  { file: "0150_GeneralUserGS_sf2_file", program: 15, name: "Dulcimer", family: "Chromatic Percussion" },
  { file: "0160_GeneralUserGS_sf2_file", program: 16, name: "Drawbar Organ", family: "Organ" },
  { file: "0170_GeneralUserGS_sf2_file", program: 17, name: "Percussive Organ", family: "Organ" },
  { file: "0180_GeneralUserGS_sf2_file", program: 18, name: "Rock Organ", family: "Organ" },
  { file: "0190_GeneralUserGS_sf2_file", program: 19, name: "Church Organ", family: "Organ" },
  { file: "0200_GeneralUserGS_sf2_file", program: 20, name: "Reed Organ", family: "Organ" },
  { file: "0210_GeneralUserGS_sf2_file", program: 21, name: "Accordion", family: "Organ" },
  { file: "0220_GeneralUserGS_sf2_file", program: 22, name: "Harmonica", family: "Organ" },
  { file: "0230_GeneralUserGS_sf2_file", program: 23, name: "Tango Accordion", family: "Organ" },
  { file: "0240_GeneralUserGS_sf2_file", program: 24, name: "Acoustic Guitar (nylon)", family: "Guitar" },
  { file: "0250_GeneralUserGS_sf2_file", program: 25, name: "Acoustic Guitar (steel)", family: "Guitar" },
  { file: "0260_GeneralUserGS_sf2_file", program: 26, name: "Electric Guitar (jazz)", family: "Guitar" },
  { file: "0270_GeneralUserGS_sf2_file", program: 27, name: "Electric Guitar (clean)", family: "Guitar" },
  { file: "0280_GeneralUserGS_sf2_file", program: 28, name: "Electric Guitar (muted)", family: "Guitar" },
  { file: "0290_GeneralUserGS_sf2_file", program: 29, name: "Overdriven Guitar", family: "Guitar" },
  { file: "0300_GeneralUserGS_sf2_file", program: 30, name: "Distortion Guitar", family: "Guitar" },
  { file: "0310_GeneralUserGS_sf2_file", program: 31, name: "Guitar Harmonics", family: "Guitar" },
  { file: "0320_GeneralUserGS_sf2_file", program: 32, name: "Acoustic Bass", family: "Bass" },
  { file: "0330_GeneralUserGS_sf2_file", program: 33, name: "Electric Bass (finger)", family: "Bass" },
  { file: "0340_GeneralUserGS_sf2_file", program: 34, name: "Electric Bass (pick)", family: "Bass" },
  { file: "0350_GeneralUserGS_sf2_file", program: 35, name: "Fretless Bass", family: "Bass" },
  { file: "0360_GeneralUserGS_sf2_file", program: 36, name: "Slap Bass 1", family: "Bass" },
  { file: "0370_GeneralUserGS_sf2_file", program: 37, name: "Slap Bass 2", family: "Bass" },
  { file: "0380_GeneralUserGS_sf2_file", program: 38, name: "Synth Bass 1", family: "Bass" },
  { file: "0390_GeneralUserGS_sf2_file", program: 39, name: "Synth Bass 2", family: "Bass" },
  { file: "0400_GeneralUserGS_sf2_file", program: 40, name: "Violin", family: "Strings" },
  { file: "0410_GeneralUserGS_sf2_file", program: 41, name: "Viola", family: "Strings" },
  { file: "0420_GeneralUserGS_sf2_file", program: 42, name: "Cello", family: "Strings" },
  { file: "0430_GeneralUserGS_sf2_file", program: 43, name: "Contrabass", family: "Strings" },
  { file: "0440_GeneralUserGS_sf2_file", program: 44, name: "Tremolo Strings", family: "Strings" },
  { file: "0450_GeneralUserGS_sf2_file", program: 45, name: "Pizzicato Strings", family: "Strings" },
  { file: "0460_GeneralUserGS_sf2_file", program: 46, name: "Orchestral Harp", family: "Strings" },
  { file: "0470_GeneralUserGS_sf2_file", program: 47, name: "Timpani", family: "Strings" },
  { file: "0480_GeneralUserGS_sf2_file", program: 48, name: "String Ensemble 1", family: "Ensemble" },
  { file: "0490_GeneralUserGS_sf2_file", program: 49, name: "String Ensemble 2", family: "Ensemble" },
  { file: "0500_GeneralUserGS_sf2_file", program: 50, name: "Synth Strings 1", family: "Ensemble" },
  { file: "0510_GeneralUserGS_sf2_file", program: 51, name: "Synth Strings 2", family: "Ensemble" },
  { file: "0520_GeneralUserGS_sf2_file", program: 52, name: "Choir Aahs", family: "Ensemble" },
  { file: "0530_GeneralUserGS_sf2_file", program: 53, name: "Voice Oohs", family: "Ensemble" },
  { file: "0540_GeneralUserGS_sf2_file", program: 54, name: "Synth Voice", family: "Ensemble" },
  { file: "0550_GeneralUserGS_sf2_file", program: 55, name: "Orchestra Hit", family: "Ensemble" },
  { file: "0560_GeneralUserGS_sf2_file", program: 56, name: "Trumpet", family: "Brass" },
  { file: "0570_GeneralUserGS_sf2_file", program: 57, name: "Trombone", family: "Brass" },
  { file: "0580_GeneralUserGS_sf2_file", program: 58, name: "Tuba", family: "Brass" },
  { file: "0590_GeneralUserGS_sf2_file", program: 59, name: "Muted Trumpet", family: "Brass" },
  { file: "0600_GeneralUserGS_sf2_file", program: 60, name: "French Horn", family: "Brass" },
  { file: "0610_GeneralUserGS_sf2_file", program: 61, name: "Brass Section", family: "Brass" },
  { file: "0620_GeneralUserGS_sf2_file", program: 62, name: "Synth Brass 1", family: "Brass" },
  { file: "0630_GeneralUserGS_sf2_file", program: 63, name: "Synth Brass 2", family: "Brass" },
  { file: "0640_GeneralUserGS_sf2_file", program: 64, name: "Soprano Sax", family: "Reed" },
  { file: "0650_GeneralUserGS_sf2_file", program: 65, name: "Alto Sax", family: "Reed" },
  { file: "0660_GeneralUserGS_sf2_file", program: 66, name: "Tenor Sax", family: "Reed" },
  { file: "0670_GeneralUserGS_sf2_file", program: 67, name: "Baritone Sax", family: "Reed" },
  { file: "0680_GeneralUserGS_sf2_file", program: 68, name: "Oboe", family: "Reed" },
  { file: "0690_GeneralUserGS_sf2_file", program: 69, name: "English Horn", family: "Reed" },
  { file: "0700_GeneralUserGS_sf2_file", program: 70, name: "Bassoon", family: "Reed" },
  { file: "0710_GeneralUserGS_sf2_file", program: 71, name: "Clarinet", family: "Reed" },
  { file: "0720_GeneralUserGS_sf2_file", program: 72, name: "Piccolo", family: "Pipe" },
  { file: "0730_GeneralUserGS_sf2_file", program: 73, name: "Flute", family: "Pipe" },
  { file: "0740_GeneralUserGS_sf2_file", program: 74, name: "Recorder", family: "Pipe" },
  { file: "0750_GeneralUserGS_sf2_file", program: 75, name: "Pan Flute", family: "Pipe" },
  { file: "0760_GeneralUserGS_sf2_file", program: 76, name: "Blown Bottle", family: "Pipe" },
  { file: "0770_GeneralUserGS_sf2_file", program: 77, name: "Shakuhachi", family: "Pipe" },
  { file: "0780_GeneralUserGS_sf2_file", program: 78, name: "Whistle", family: "Pipe" },
  { file: "0790_GeneralUserGS_sf2_file", program: 79, name: "Ocarina", family: "Pipe" },
  { file: "0800_GeneralUserGS_sf2_file", program: 80, name: "Lead 1 (square)", family: "Synth Lead" },
  { file: "0810_GeneralUserGS_sf2_file", program: 81, name: "Lead 2 (sawtooth)", family: "Synth Lead" },
  { file: "0820_GeneralUserGS_sf2_file", program: 82, name: "Lead 3 (calliope)", family: "Synth Lead" },
  { file: "0830_GeneralUserGS_sf2_file", program: 83, name: "Lead 4 (chiff)", family: "Synth Lead" },
  { file: "0840_GeneralUserGS_sf2_file", program: 84, name: "Lead 5 (charang)", family: "Synth Lead" },
  { file: "0850_GeneralUserGS_sf2_file", program: 85, name: "Lead 6 (voice)", family: "Synth Lead" },
  { file: "0860_GeneralUserGS_sf2_file", program: 86, name: "Lead 7 (fifths)", family: "Synth Lead" },
  { file: "0870_GeneralUserGS_sf2_file", program: 87, name: "Lead 8 (bass + lead)", family: "Synth Lead" },
  { file: "0880_GeneralUserGS_sf2_file", program: 88, name: "Pad 1 (new age)", family: "Synth Pad" },
  { file: "0890_GeneralUserGS_sf2_file", program: 89, name: "Pad 2 (warm)", family: "Synth Pad" },
  { file: "0900_GeneralUserGS_sf2_file", program: 90, name: "Pad 3 (polysynth)", family: "Synth Pad" },
  { file: "0910_GeneralUserGS_sf2_file", program: 91, name: "Pad 4 (choir)", family: "Synth Pad" },
  { file: "0920_GeneralUserGS_sf2_file", program: 92, name: "Pad 5 (bowed)", family: "Synth Pad" },
  { file: "0930_GeneralUserGS_sf2_file", program: 93, name: "Pad 6 (metallic)", family: "Synth Pad" },
  { file: "0940_GeneralUserGS_sf2_file", program: 94, name: "Pad 7 (halo)", family: "Synth Pad" },
  { file: "0950_GeneralUserGS_sf2_file", program: 95, name: "Pad 8 (sweep)", family: "Synth Pad" },
  { file: "0960_GeneralUserGS_sf2_file", program: 96, name: "FX 1 (rain)", family: "Synth Effects" },
  { file: "0970_GeneralUserGS_sf2_file", program: 97, name: "FX 2 (soundtrack)", family: "Synth Effects" },
  { file: "0980_GeneralUserGS_sf2_file", program: 98, name: "FX 3 (crystal)", family: "Synth Effects" },
  { file: "0990_GeneralUserGS_sf2_file", program: 99, name: "FX 4 (atmosphere)", family: "Synth Effects" },
  { file: "1000_GeneralUserGS_sf2_file", program: 100, name: "FX 5 (brightness)", family: "Synth Effects" },
  { file: "1010_GeneralUserGS_sf2_file", program: 101, name: "FX 6 (goblins)", family: "Synth Effects" },
  { file: "1020_GeneralUserGS_sf2_file", program: 102, name: "FX 7 (echoes)", family: "Synth Effects" },
  { file: "1030_GeneralUserGS_sf2_file", program: 103, name: "FX 8 (sci-fi)", family: "Synth Effects" },
  { file: "1040_GeneralUserGS_sf2_file", program: 104, name: "Sitar", family: "Ethnic" },
  { file: "1050_GeneralUserGS_sf2_file", program: 105, name: "Banjo", family: "Ethnic" },
  { file: "1060_GeneralUserGS_sf2_file", program: 106, name: "Shamisen", family: "Ethnic" },
  { file: "1070_GeneralUserGS_sf2_file", program: 107, name: "Koto", family: "Ethnic" },
  { file: "1080_GeneralUserGS_sf2_file", program: 108, name: "Kalimba", family: "Ethnic" },
  { file: "1090_GeneralUserGS_sf2_file", program: 109, name: "Bagpipe", family: "Ethnic" },
  { file: "1100_GeneralUserGS_sf2_file", program: 110, name: "Fiddle", family: "Ethnic" },
  { file: "1110_GeneralUserGS_sf2_file", program: 111, name: "Shanai", family: "Ethnic" },
  { file: "1120_GeneralUserGS_sf2_file", program: 112, name: "Tinkle Bell", family: "Percussive" },
  { file: "1130_GeneralUserGS_sf2_file", program: 113, name: "Agogo", family: "Percussive" },
  { file: "1140_GeneralUserGS_sf2_file", program: 114, name: "Steel Drums", family: "Percussive" },
  { file: "1150_GeneralUserGS_sf2_file", program: 115, name: "Woodblock", family: "Percussive" },
  { file: "1160_GeneralUserGS_sf2_file", program: 116, name: "Taiko Drum", family: "Percussive" },
  { file: "1170_GeneralUserGS_sf2_file", program: 117, name: "Melodic Tom", family: "Percussive" },
  { file: "1180_GeneralUserGS_sf2_file", program: 118, name: "Synth Drum", family: "Percussive" },
  { file: "1190_GeneralUserGS_sf2_file", program: 119, name: "Reverse Cymbal", family: "Percussive" },
  { file: "1200_GeneralUserGS_sf2_file", program: 120, name: "Guitar Fret Noise", family: "Sound Effects" },
  { file: "1210_GeneralUserGS_sf2_file", program: 121, name: "Breath Noise", family: "Sound Effects" },
  { file: "1220_GeneralUserGS_sf2_file", program: 122, name: "Seashore", family: "Sound Effects" },
  { file: "1230_GeneralUserGS_sf2_file", program: 123, name: "Bird Tweet", family: "Sound Effects" },
  { file: "1240_GeneralUserGS_sf2_file", program: 124, name: "Telephone Ring", family: "Sound Effects" },
  { file: "1250_GeneralUserGS_sf2_file", program: 125, name: "Helicopter", family: "Sound Effects" },
  { file: "1260_GeneralUserGS_sf2_file", program: 126, name: "Applause", family: "Sound Effects" },
  { file: "1270_GeneralUserGS_sf2_file", program: 127, name: "Gunshot", family: "Sound Effects" },
];

export const WAF_FAMILIES = ["Piano","Chromatic Percussion","Organ","Guitar","Bass","Strings","Ensemble","Brass","Reed","Pipe","Synth Lead","Synth Pad","Synth Effects","Ethnic","Percussive","Sound Effects"];
